api/core/scrapers/__init__.py, api/core/scrapers/indeed/__init__.py, api/core/scrapers/linkedin/__init__.py, api/core/scrapers/ziprecruiter/__init__.py
**This pull request makes the following changes.**
* Fixes issue #11
=> Fix full description

pyproject.toml, src/jobspy/__init__.py, src/jobspy/scrapers/indeed/__init__.py, src/tests/test_all.py, src/tests/test_indeed.py, src/tests/test_linkedin.py
=> - refactor & #41 bug fix

JobSpy_Demo.ipynb, README.md, pyproject.toml, src/jobspy/__init__.py, src/jobspy/jobs/__init__.py, src/jobspy/scrapers/__init__.py, src/jobspy/scrapers/exceptions.py, src/jobspy/scrapers/indeed/__init__.py, src/jobspy/scrapers/linkedin/__init__.py, src/jobspy/scrapers/ziprecruiter/__init__.py
=> Proxy support

pyproject.toml, src/jobspy/scrapers/indeed/__init__.py
=> [fix] indeed - min & max values swapped

pyproject.toml, src/jobspy/scrapers/linkedin/__init__.py, src/jobspy/scrapers/utils.py
Addresses #25 issue
The salary data exists on the main jobs list page.
=> added salary data for linkedin

pyproject.toml, src/jobspy/scrapers/linkedin/__init__.py
Hey, hope this makes sense.
for some of my jobs i couldnt get the location as the location were in this format `Padstow, New South Wales, Australia`
so had to modify this
=> include location with 3 parts

pyproject.toml, src/jobspy/jobs/__init__.py, src/jobspy/scrapers/glassdoor/__init__.py, src/jobspy/scrapers/indeed/__init__.py, src/jobspy/scrapers/linkedin/__init__.py, src/jobspy/scrapers/utils.py, src/jobspy/scrapers/ziprecruiter/__init__.py
=> fix: clean description

README.md, src/jobspy/jobs/__init__.py, src/jobspy/scrapers/glassdoor/__init__.py, src/jobspy/scrapers/indeed/__init__.py, src/jobspy/scrapers/linkedin/__init__.py, src/jobspy/scrapers/utils.py, src/jobspy/scrapers/ziprecruiter/__init__.py
Tried to fix glassdoor timeout exceptions. Still stops program when triggered.
=> created console search updates, tried to fix glassdoor timeout exception

README.md, src/jobspy/__init__.py, src/jobspy/scrapers/utils.py
I often don't want any logs printed when the code is executed, so being able to control the verbosity is useful for me.
=> feat: Adjust log verbosity via verbose arg

src/jobspy/__init__.py, src/jobspy/jobs/__init__.py, src/jobspy/scrapers/glassdoor/__init__.py, src/jobspy/scrapers/indeed/__init__.py, src/jobspy/scrapers/linkedin/__init__.py, src/jobspy/scrapers/ziprecruiter/__init__.py
=> chore: id added for JobPost schema

src/jobspy/scrapers/linkedin/__init__.py
Correct initial page offset calculation
Separate page variable from request counter
Fix job offset starting value
Increment offset by number of jobs returned instead of expected value
=> Issue #158

pyproject.toml, src/jobspy/scrapers/linkedin/__init__.py, src/jobspy/scrapers/utils.py, src/jobspy/scrapers/ziprecruiter/__init__.py
=> enh: ziprecruiter full description

pyproject.toml, src/jobspy/__init__.py, src/jobspy/scrapers/glassdoor/__init__.py, src/jobspy/scrapers/indeed/__init__.py, src/jobspy/scrapers/linkedin/__init__.py, src/jobspy/scrapers/utils.py, src/jobspy/scrapers/ziprecruiter/__init__.py
=> Salary parse

src/jobspy/scrapers/glassdoor/__init__.py
Add Glassdoor logo data if available in order to have a more complete `JobPost` information
=> FEAT: Add Glassdoor logo data if available

README.md, src/jobspy/__init__.py, src/jobspy/jobs/__init__.py, src/jobspy/scrapers/linkedin/__init__.py
Added new attributes (**job_level**) to job data models for **LinkedIn**
Added **job level** parser for **LinkedIn**
Added **company industry** parser for **LinkedIn**
=> Add company industry and job level to linkedin scraper

pyproject.toml, src/jobspy/scrapers/indeed/__init__.py
=> enh: estimated salary

pyproject.toml, src/jobspy/__init__.py
=> fix:key error

.github/workflows/python-test.yml, pyproject.toml, src/jobspy/jobs/__init__.py, src/tests/test_all.py
=> fix:malaysia indeed

.github/workflows/python-test.yml, tests/test_all.py, tests/test_glassdoor.py, tests/test_indeed.py, tests/test_linkedin.py, tests/test_ziprecruiter.py
=> fix: extract tests out of src

jobspy/__init__.py, jobspy/bdjobs/__init__.py, jobspy/bdjobs/constant.py, jobspy/bdjobs/util.py, jobspy/exception.py, jobspy/model.py
=> Bdjobs Fixed
